[package]
name = "process_info"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.38.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"


[[bin]]
name = "agent"
path = "src/agent.rs"

[[bin]]
name = "viewer"
path = "src/viewer.rs"